# Generated by Django 5.0 on 2024-12-02 08:28

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("essay_text", tinymce.models.HTMLField()),
                (
                    "essay_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evaluations/files/",
                        verbose_name="Uploaded File",
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Evaluated On"
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Evaluation Score"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="Feedback"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
